server {
    listen          80;
    server_name     pipeline.*;

    location /.well-known/acme-challenge/ {
        resolver    127.0.0.11 valid=30s;
        set         $upstream_certbot certbot;
        proxy_pass  http://$upstream_certbot$request_uri;
    }

    location / {
        resolver    127.0.0.11 valid=30s;
        set         $upstream_pipeline pipeline_streaming-pipeline;
        proxy_pass  http://$upstream_pipeline:8080;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
server {
    listen          443 ssl;
    listen          [::]:443 ssl;
    server_name     pipeline.*;

    location /.well-known/acme-challenge/ {
        resolver    127.0.0.11 valid=30s;
        set         $upstream_certbot certbot;
        proxy_pass  http://$upstream_certbot$request_uri;
    }

    location / {
        resolver    127.0.0.11 valid=30s;
        set         $upstream_pipeline pipeline_streaming-pipeline;
        proxy_pass  http://$upstream_pipeline:8080;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
