# fhir-data-pipes control panel for iSantePlus pipeline #1
server {
    listen                80;
    server_name           pipeline-isanteplus1.*;

    location /.well-known/acme-challenge/ {
        resolver          127.0.0.11 valid=30s;
        set               $upstream_certbot certbot;
        proxy_pass        http://$upstream_certbot$request_uri;
    }

    location / {
        return            301 https://$host$request_uri;
    }
}
server {
    listen                443 ssl;
    listen                [::]:443 ssl;
    server_name           pipeline-isanteplus1.*;
    client_max_body_size  50M;

    location /.well-known/acme-challenge/ {
        resolver          127.0.0.11 valid=30s;
        set               $upstream_certbot certbot;
        proxy_pass        http://$upstream_certbot$request_uri;
    }

    location / {
        resolver          127.0.0.11 valid=30s;
        set               $upstream_pipeline_isanteplus1 pipeline_pipeline-isanteplus1;
        proxy_pass        http://$upstream_pipeline_isanteplus1:8080;
        proxy_set_header  Host              $host;
        proxy_set_header  X-Real-IP         $remote_addr;
        proxy_set_header  X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header  X-Forwarded-Proto $scheme;
    }
}

# fhir-data-pipes control panel for iSantePlus pipeline #2
server {
    listen                80;
    server_name           pipeline-isanteplus2.*;

    location /.well-known/acme-challenge/ {
        resolver          127.0.0.11 valid=30s;
        set               $upstream_certbot certbot;
        proxy_pass        http://$upstream_certbot$request_uri;
    }

    location / {
        return            301 https://$host$request_uri;
    }
}
server {
    listen                443 ssl;
    listen                [::]:443 ssl;
    server_name           pipeline-isanteplus2.*;
    client_max_body_size  50M;

    location /.well-known/acme-challenge/ {
        resolver          127.0.0.11 valid=30s;
        set               $upstream_certbot certbot;
        proxy_pass        http://$upstream_certbot$request_uri;
    }

    location / {
        resolver          127.0.0.11 valid=30s;
        set               $upstream_pipeline_isanteplus2 pipeline_pipeline-isanteplus2;
        proxy_pass        http://$upstream_pipeline_isanteplus2:8080;
        proxy_set_header  Host              $host;
        proxy_set_header  X-Real-IP         $remote_addr;
        proxy_set_header  X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header  X-Forwarded-Proto $scheme;
    }
}
