version: "3.9"

services:
  streaming-pipeline:
    image: us-docker.pkg.dev/cloud-build-fhir/fhir-analytics/main:latest
    environment:
      - JAVA_OPTS=-Xms2g -Xmx2g
      - FLINK_CONF_DIR=/app/config
      - fhirdata.fhirServerUrl=http://isanteplus:8080/openmrs/ws/fhir2/R4
      - fhirdata.dwhRootPrefix=/dwh/pipeline_DWH
    configs:
      - source: application_yaml
        target: /app/config/application.yaml
      - source: flink_conf_yaml
        target: /app/config/flink-conf.yaml
    volumes:
      - pipeline-dwh:/dwh
    ports:
      - target: 8080
        published: 8095
        protocol: tcp
        mode: host
    networks:
      - openhim
      - shr
      - isanteplus
      - hapi-fhir

  streaming-pipeline-2:
    image: us-docker.pkg.dev/cloud-build-fhir/fhir-analytics/main:latest
    environment:
      - JAVA_OPTS=-Xms2g -Xmx2g
      - FLINK_CONF_DIR=/app/config
      - fhirdata.fhirServerUrl=http://isanteplus2:8080/openmrs/ws/fhir2/R4
      - fhirdata.dwhRootPrefix=/dwh/pipeline_DWH2
    configs:
      - source: application_yaml
        target: /app/config/application.yaml
      - source: flink_conf_yaml
        target: /app/config/flink-conf.yaml
    volumes:
      - pipeline-dwh-2:/dwh
    ports:
      - target: 8080
        published: 8096
        protocol: tcp
        mode: host
    networks:
      - openhim
      - shr
      - isanteplus
      - hapi-fhir

  streaming-pipeline-3:
    image: us-docker.pkg.dev/cloud-build-fhir/fhir-analytics/main:latest
    environment:
      - JAVA_OPTS=-Xms2g -Xmx2g
      - FLINK_CONF_DIR=/app/config
      - fhirdata.fhirServerUrl=http://isanteplus3:8080/openmrs/ws/fhir2/R4
      - fhirdata.dwhRootPrefix=/dwh/pipeline_DWH3
    configs:
      - source: application_yaml
        target: /app/config/application.yaml
      - source: flink_conf_yaml
        target: /app/config/flink-conf.yaml
    volumes:
      - pipeline-dwh-3:/dwh
    ports:
      - target: 8080
        published: 8097
        protocol: tcp
        mode: host
    networks:
      - openhim
      - shr
      - isanteplus
      - hapi-fhir

  streaming-pipeline-4:
    image: us-docker.pkg.dev/cloud-build-fhir/fhir-analytics/main:latest
    environment:
      - JAVA_OPTS=-Xms2g -Xmx2g
      - FLINK_CONF_DIR=/app/config
      - fhirdata.fhirServerUrl=http://isanteplus4:8080/openmrs/ws/fhir2/R4
      - fhirdata.dwhRootPrefix=/dwh/pipeline_DWH4
    configs:
      - source: application_yaml
        target: /app/config/application.yaml
      - source: flink_conf_yaml
        target: /app/config/flink-conf.yaml
    volumes:
      - pipeline-dwh-4:/dwh
    ports:
      - target: 8080
        published: 8098
        protocol: tcp
        mode: host
    networks:
      - openhim
      - shr
      - isanteplus
      - hapi-fhir

configs:
  application_yaml:
    file: ./config/application.yaml
    name: pipeline_application_yaml
    labels:
      name: pipeline_application_yaml
  flink_conf_yaml:
    file: ./config/flink-conf.yaml
    name: pipeline_flink_conf_yaml
    labels:
      name: pipeline_flink_conf_yaml

volumes:
  pipeline-dwh:
  pipeline-dwh-2:
  pipeline-dwh-3:
  pipeline-dwh-4:

networks:
  openhim:
    name: openhim_public
    external: true
  shr:
    name: shr
    external: true
  mysql:
    name: mysql_public
    external: true
  isanteplus:
    name: isanteplus_public
    external: true
  hapi-fhir:
    name: hapi-fhir_public
    external: true
