version: "3.9"

services:
  streaming-pipeline:
    image: us-docker.pkg.dev/cloud-build-fhir/fhir-analytics/main:latest
    environment:
      - JAVA_OPTS=-Xms2g -Xmx2g
      - FLINK_CONF_DIR=/app/config
    volumes:
      - ./config:/app/config:ro
      - pipeline-dwh:/dwh
    ports:
      - target: 8080
        published: 8095
        protocol: tcp
        mode: host
    networks:
      - openhim
      - shr
      - isanteplus
      - hapi-fhir

volumes:
  pipeline-dwh:

networks:
  openhim:
    name: openhim_public
    external: true
  shr:
    name: shr
    external: true
  mysql:
    name: mysql_public
    external: true
  isanteplus:
    name: isanteplus_public
    external: true
  hapi-fhir:
    name: hapi-fhir_public
    external: true
