fhirdata:
  fhirFetchMode: "FHIR_SEARCH"

  fhirServerUrl: "http://isanteplus2:8080/openmrs/ws/fhir2/R4"
  fhirServerUserName: "admin"
  fhirServerPassword: "Admin123"

  sinkFhirServerUrl: "http://openhim-core:5001/SHR/fhir"
  sinkUserName: "shr-pipeline"
  sinkPassword: "instant101"
  sinkDbConfigPath:

  dwhRootPrefix: "/dwh/pipeline_DWH"
  generateParquetFiles: false

  incrementalSchedule: "0 0 * * * *"
  purgeSchedule: "0 30 * * * *"
  numOfDwhSnapshotsToRetain: 2

  resourceList: "Practitioner,Location,Patient,Encounter,Observation,Condition,AllergyIntolerance,MedicationRequest,Group"

  fhirVersion: "R4"
  numThreads: 1

  autoGenerateFlinkConfiguration: true
  rowGroupSizeForParquetFiles: 33554432
  recursiveDepth: 1
  structureDefinitionsPath: "classpath:/r4-us-core-definitions"
  createHiveResourceTables: false
  createParquetViews: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,pipeline-metrics
