# Prevents "Insufficient number of network buffers" with many workers
taskmanager.memory.network.max: 256mb

# Prevents "record exceeds the maximum size of a sort buffer" in JDBC mode
taskmanager.memory.managed.size: 256mb

# Makes pipeline.run() non-blocking with FlinkRunner
execution.attached: false

# Required to track pipeline metrics when FlinkRunner is used
execution.job-listeners: com.google.fhir.analytics.metrics.FlinkJobListener
